name: patrol_shield_admin
description: PatrolShield Flutter Web Admin Dashboard
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  state_notifier: ^1.0.0
  
  # HTTP Client
  dio: ^5.4.0
  
  # WebSocket
  web_socket_channel: ^3.0.1
  
  # Navigation
  go_router: ^16.1.0
  
  # UI Components
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  
  # Utils
  json_annotation: ^4.8.1
  intl: ^0.20.2
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.0.0
  
  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  
  # Linting
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - .env